export enum EOblasts {
    CHERKASY_OBLAST = "cherkasy-oblast",
    CHERNIHIV_OBLAST = "chernihiv-oblast",
    CHERNIVTSI_OBLAST = "chernivtsi-oblast",
    DNIPROPETROVSK_OBLAST = "dnipropetrovsk-oblast",
    DONETSK_OBLAST = "donetsk -oblast",
    IVANO_FRANKIVSK_OBLAST = "ivano-frankivsk-oblast",
    KHARKIV_OBLAST = "kharkiv-oblast",
    KHERSON_OBLAST = "kherson-oblast",
    KHMELNYTSKYI_OBLAST = "khmelnytskyi-oblast",
    KIROVOHRAD_OBLAST = "kirovohrad-oblast",
    KYIV_OBLAST = "kyiv-oblast",
    LUHANSK_OBLAST = "luhansk-oblast",
    LVIV_OBLAST = "lviv-oblast",
    MYKOLAIV_OBLAST = "mykolaiv-oblast",
    ODESA_OBLAST = "odesa-oblast",
    POLTAVA_OBLAST = "poltava-oblast",
    RIVNE_OBLAST = "rivne-oblast",
    SUMY_OBLAST = "sumy-oblast",
    TERNOPIL_OBLAST = "ternopil-oblast",
    VINNYTSIA_OBLAST = "vinnytsia-oblast",
    VOLYN_OBLAST = "volyn-oblast",
    ZAKARPATTIA_OBLAST = "zakarpattia-oblast",
    ZAPORIZHZHIA_OBLAST = "zaporizhzhia-oblast",
    ZHYTOMYR_OBLAST = "zhytomyr-oblast",
}